name: 'Security Hub Visibility'
description: 'Syncs AWS Security Hub findings with Jira issues'
author: 'MAC-FC'
inputs:
  # The application has its own built in default values for unset inputs. Double check index.ts for the current default values.
  # Jira
  jira-base-uri:
    description: 'URI of the target Jira API endpoint'
    required: false
    # Application Default - https://jiraent.cms.gov
  jira-username:
    description: 'Jira username that will be the reporter of issues created when syncing'
    required: true
  jira-token:
    description: 'Jira token corresponding to the jira-username input with permission to manage issues for the target Jira project'
    required: true
  jira-project-key:
    description: 'Jira project key where issues will be created'
    required: true
  jira-ignore-statuses:
    description: 'Comma-separated list of Jira issue statuses that will be ignore when syncing'
    required: false
    # Application Default - "Done, Closed, Resolved"
  jira-assignee:
    description: 'the assignee accountId to assign the Jira ticket to'
    required: false
  jira-transition-map:
    description: 'JSON string of Jira statuses and transition pairs to traverse when closing an issue e.g "To Do:Start Progress, In Progress:Done"'
    required: false
    # Application Default - '*: DONE'
  jira-custom-fields:
    description: 'JSON string of Jira custom field keys/values, e.g. { "customfield_14117": "example-value" }'
  jira-watchers:
    description: 'Comma separated list of Emails for Atlassion Jira and User EUA IDs for Enterprise Jira '
    required: false
    default: ''
  jira-add-labels:
    description: 'Comma separated list of labels to add in newly created tickets'
    default: ''
# AWS
  aws-region:
    description: 'Target AWS region for Security Hub findings'
    required: false
    # Application Default: us-east-1
  aws-severities:
    description: 'Comma-separated list of Security Hub finding severities to sync'
    required: false
    # Application Default - 'CRITICAL,HIGH,MEDIUM'
  auto-close:
    description: 'a boolean to support auto closing for issue'
    required: false
    # Application Default - true
  dry-run-test-data:
    description: 'a boolean to support dry run of tickets creation'
    required: false
    # Application Default - false
  jira-link-id:
    description: 'the new created issue will be linked to this link id'
    required: false
  jira-link-type:
    description: "this defines the relation of the new issue with feature issue specified and default value for this is 'Relates'"
    required: false
  jira-link-direction:
    description: "this variable is to specify the direction of linked issue either inward or outward"
    required: false
  include-all-products:
    description: "a boolean to enable findings from other products"
    required: false
  skip-products:
    description: "comma separated list of product names for those the findings should be skipped"
    required: false
  jira-labels-config:
    description: "This variable is to specify stringified labels config"
    required: false
  jira-consolidate-tickets:
    description: "True/False value to enable/disable the consolidation of tickets"
    required: false
  test-findings-data:
    description: "JSON string of findings list"
    required: false
outputs:
  updates:
    description: "List of urls of created issues"
  total:
    description: "count of updates"
  created:
    description: "count of created issues"
  closed:
    description: "count of closed issues"
  jql:
    description: "the jql query for new updates"
runs:
  using: 'node20'
  main: 'dist/index.js'
