name: 'Security Hub Visibility'
description: 'Syncs AWS Security Hub findings with Jira issues'
author: 'MAC-FC'
inputs:
  # Jira
  jira-base-uri:
    description: 'URI of the target Jira API endpoint'
    required: false
    # Default - https://jiraent.cms.gov
  jira-username:
    description: 'Jira username that will be the reporter of issues created when syncing'
    required: true
  jira-token:
    description: 'Jira token corresponding to the jira-username input with permission to manage issues for the target Jira project'
    required: true
  jira-project-key:
    description: 'Jira project key where issues will be created'
    required: true
  jira-ignored-statuses:
    description: 'Comma-separated list of Jira issue statuses that will be ignored when syncing'
    required: false
    # Default - "Done, Closed, Resolved"
  jira-assignee:
    description: 'the assignee accountId to assign the Jira ticket to'
    required: false
  jira-transition-map:
    description: 'JSON string of Jira statuses and transition pairs to traverse when closing an issue e.g 'To Do:Start Progress, In Progress:Done'
    required: false
    # Default - '*: DONE'
  jira-epic-key:
    description: 'Jira epic key where issues will be created'
    required: false
  jira-custom-fields:
    description: 'JSON string of Jira custom field keys/values, e.g. { "customfield_14117": "example-value" }'
# AWS
  aws-region:
    description: 'Target AWS region for Security Hub findings'
    required: false
    # Default: us-east-1
  aws-severities:
    description: 'Comma-separated list of Security Hub finding severities to sync'
    required: false
    # Default - 'Done, Closed, Resolved'
  auto-close:
    description: 'a boolean to support auto closing for issue'
    required: false
    # Default - true
  dry-run:
    description: 'a boolean to support dry run'
    required: false
    # Default - false

runs:
  using: 'node20'
  main: 'dist/index.js'
