name: Check that module was built

on:
  push:
    branches:
      - main
      - zarate-test-workflow
  pull_request:
  workflow_dispatch:

jobs:
  check-dist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install dos2unix
        run: sudo apt-get install dos2unix

      - name: Install dependencies
        run: pnpm install

      - name: Build the dist/ directory
        run: pnpm run build

      - name: Normalize line endings and whitespace
        run: |
          find dist -type f -exec dos2unix {} \;
          find dist -type f -exec sed -i 's/[[:space:]]\+$//' {} \;

      - name: Check for uncommitted changes in dist/
        run: |
          if git diff --ignore-all-space --ignore-blank-lines --exit-code dist; then
            echo "No changes detected in the dist/ directory."
          else
            echo "Detected uncommitted changes after building. Please run 'pnpm run build' and commit the changes."
            exit 1
          fi
        shell: bash
