name: Check that module was built

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  check-dist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Build the dist/ directory
        run: npm run build

      - name: Check for diff
        run: |
          if [ -z "$(git status --porcelain dist/)" ]; then
            echo "No uncommitted changes in dist/. Everything is clean."
          else
            echo "Detected uncommitted changes in dist/ after building. Please run 'npm run build' and commit the changes."
            git status --porcelain dist
            exit 1
          fi
