name: Check that module was built

on:
  push:
    branches:
      - main
      - zarate-test-workflow
  pull_request:
  workflow_dispatch:

jobs:
  check-dist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Install diffoscope
        run: |
          sudo apt-get update
          sudo apt-get install -y diffoscope

      - name: Build the dist/ directory
        run: pnpm run build

      - name: Check for uncommitted changes in dist/
        run: |
          if git diff --exit-code dist; then
            echo "Detected uncommitted changes after building. Please run 'pnpm run build' and commit the changes."
            diffoscope dist dist-original > diffoscope-report.txt || true
            echo "Differences in binary files:" && cat diffoscope-report.txt
            exit 1
          else
            echo "No changes detected in the dist/ directory."
          fi
        shell: bash
