name: Check that module was built

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check-dist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Build the dist/ directory
        run: npm run build

      - name: Check for diff
        run: |
          if git diff --no-patch --exit-code dist; then
            echo "Detected uncommitted changes after building. Please run 'npm run build' and commit the changes."
            exit 1
          fi
