name: Check that module was built

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check-dist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Build the dist/ directory
        run: pnpm build

      - name: Check for diff
        run: |
          if git diff --exit-code dist; then
            echo "No changes detected in the dist/ directory."
          else
            echo "Detected uncommitted changes after building. Please run 'pnpm run build' and commit the changes."
            exit 1
          fi
