name: Sync Security Hub findings and Jira issues V2
on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  sync:
    strategy:
      max-parallel: 1
      matrix:
        environment: ["dev"]
      fail-fast: false
    environment:
      name: ${{ matrix.environment }}
    name: Run sync
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_TO_ASSUME }}
      - name: Sync Security Hub and Jira
        uses: Enterprise-CMCS/mac-fc-security-hub-visibility@v2.0.8
        with:
          jira-token: ${{ secrets.JIRA_TEST_TOKEN }}
          jira-username: username # required variable for package but not for Enterprise Jira
          jira-project-key: Pj
          jira-ignore-statuses: Done, Closed, Canceled
          aws-severities: CRITICAL, HIGH, MEDIUM, LOW
          jira-link-id: ${{secrets.JIRA_LINK_ID}}
          jira-link-type: "Relates"
          include-all-products: 'true'
          jira-link-direction: 'outward'
          jira-labels-config: "[{\"labelField\":\"ProductName\",\"labelPrefix\":\"product\",\"labelDelimiter\":\":\"},{\"labelField\":\"severity\"},{\"labelField\":\"accountId\",\"labelDelimiter\":\":\",\"labelPrefix\":\"account\"},{\"labelField\":\"region\"},{\"labelField\":\"accountAlias\"}]"
         #skip-products: Health, Default 
